use crate::audio::AudioEngine;

use super::*;

impl WavesPreviewer {
    pub(super) fn build_app(startup: StartupConfig, audio: AudioEngine) -> Self {
        audio.set_loop_enabled(false);
        let ipc_rx = startup.ipc_rx.clone();
        let startup_state = StartupState::new(startup.clone());
        let debug_state = DebugState::new(startup.debug.clone());
        let mut app = Self {
            audio,
            root: None,
            items: Vec::new(),
            item_index: HashMap::new(),
            path_index: HashMap::new(),
            files: Vec::new(),
            next_media_id: 1,
            selected: None,
            volume_db: -12.0,
            audio_output_device_name: None,
            audio_output_devices: Vec::new(),
            audio_output_error: None,
            playback_rate: 1.0,
            playback_session: PlaybackSessionState::default(),
            playback_fx_state: None,
            playback_fx_job_id: 0,
            playback_source_generation: 0,
            playback_base_audio: None,
            prepared_playback_fx_audio: None,
            prepared_playback_fx_generation: 0,
            prepared_playback_fx_mode: None,
            prepared_playback_fx_rate: 1.0,
            prepared_playback_fx_pitch: 0.0,
            pitch_semitones: 0.0,
            meter_db: -80.0,
            tabs: Vec::new(),
            waveform_scratch: WaveformScratch::default(),
            active_tab: None,
            workspace_view: WorkspaceView::List,
            effect_graph: EffectGraphState::default(),
            meta_rx: None,
            meta_pool: None,
            meta_inflight: HashSet::new(),
            meta_sort_pending: false,
            meta_sort_last_applied: None,
            list_meta_prefetch_cursor: 0,
            transcript_inflight: HashSet::new(),
            transcript_ai_inflight: HashSet::new(),
            show_transcript_window: false,
            pending_transcript_seek: None,
            transcript_ai_opt_in: false,
            transcript_ai_model_dir: None,
            transcript_ai_available: false,
            transcript_ai_state: None,
            transcript_model_download_state: None,
            transcript_ai_last_error: None,
            transcript_ai_cfg: TranscriptAiConfig::default(),
            transcript_supported_languages: Vec::new(),
            transcript_supported_tasks: Vec::new(),
            music_ai_model_dir: None,
            music_ai_available: false,
            music_ai_demucs_model_path: None,
            music_ai_state: None,
            music_model_download_state: None,
            music_ai_last_error: None,
            music_ai_inflight: HashSet::new(),
            music_preview_state: None,
            music_preview_generation_counter: 0,
            music_preview_expected_generation: 0,
            external_sources: Vec::new(),
            external_active_source: None,
            external_source: None,
            external_headers: Vec::new(),
            external_rows: Vec::new(),
            external_key_index: None,
            external_key_rule: ExternalKeyRule::FileName,
            external_match_input: ExternalRegexInput::FileName,
            external_visible_columns: Vec::new(),
            external_lookup: HashMap::new(),
            external_key_row_index: HashMap::new(),
            external_match_count: 0,
            external_unmatched_count: 0,
            external_show_unmatched: false,
            external_unmatched_rows: Vec::new(),
            external_sheet_names: Vec::new(),
            external_sheet_selected: None,
            external_has_header: true,
            external_header_row: None,
            external_data_row: None,
            external_scope_regex: String::new(),
            external_settings_dirty: false,
            show_external_dialog: false,
            external_load_error: None,
            external_match_regex: String::new(),
            external_match_replace: String::new(),
            external_load_rx: None,
            external_load_inflight: false,
            external_load_rows: 0,
            external_load_started_at: None,
            external_load_path: None,
            external_load_target: None,
            external_load_queue: VecDeque::new(),
            pending_external_restore: None,
            tool_defs: Vec::new(),
            tool_queue: std::collections::VecDeque::new(),
            tool_run_rx: None,
            tool_worker_busy: false,
            tool_log: std::collections::VecDeque::new(),
            tool_log_max: 200,
            show_tool_palette: false,
            tool_search: String::new(),
            tool_selected: None,
            tool_args_overrides: HashMap::new(),
            tool_config_error: None,
            pending_tool_confirm: None,
            spectro_cache: HashMap::new(),
            spectro_inflight: HashSet::new(),
            spectro_progress: HashMap::new(),
            spectro_cancel: HashMap::new(),
            spectro_cache_order: VecDeque::new(),
            spectro_cache_sizes: HashMap::new(),
            spectro_cache_bytes: 0,
            spectro_generation: HashMap::new(),
            spectro_generation_counter: 0,
            spectro_cfg: SpectrogramConfig::default(),
            spectro_tx: None,
            spectro_rx: None,
            editor_viewport_tx: None,
            editor_viewport_rx: None,
            editor_viewport_generation_counter: 0,
            editor_feature_cache: HashMap::new(),
            editor_feature_inflight: HashSet::new(),
            editor_feature_progress: HashMap::new(),
            editor_feature_cancel: HashMap::new(),
            editor_feature_generation: HashMap::new(),
            editor_feature_generation_counter: 0,
            editor_feature_tx: None,
            editor_feature_rx: None,
            scan_rx: None,
            scan_in_progress: false,
            scan_started_at: None,
            scan_found_count: 0,
            wave_row_h: 26.0,
            list_columns: ListColumnConfig::default(),
            list_art_textures: HashMap::new(),
            show_list_art_window: false,
            list_art_window_path: None,
            list_art_window_texture: None,
            list_art_window_error: None,
            selected_multi: std::collections::BTreeSet::new(),
            select_anchor: None,
            clipboard_payload: None,
            clipboard_temp_files: Vec::new(),
            clipboard_c_was_down: false,
            clipboard_v_was_down: false,
            undo_z_was_down: false,
            list_undo_stack: Vec::new(),
            list_redo_stack: Vec::new(),
            last_undo_scope: UndoScope::Editor,
            sort_key: SortKey::File,
            sort_dir: SortDir::None,
            sort_loading_started_at: None,
            sort_loading_hold_until: None,
            sort_loading_last_ms: 0.0,
            scroll_to_selected: false,
            last_list_scroll_at: None,
            auto_play_list_nav: false,
            suppress_list_enter: false,
            list_has_focus: false,
            search_has_focus: false,
            original_files: Vec::new(),
            search_query: String::new(),
            search_use_regex: false,
            search_dirty: false,
            search_deadline: None,
            skip_dotfiles: true,
            zero_cross_epsilon: 1.0e-4,
            invert_wave_zoom_wheel: false,
            invert_shift_wheel_pan: false,
            horizontal_zoom_anchor_mode: EditorHorizontalZoomAnchorMode::Pointer,
            editor_pause_resume_mode: EditorPauseResumeMode::ReturnToLastStart,
            mode: RateMode::Speed,
            processing: None,
            processing_job_id: 0,
            list_preview_rx: None,
            list_preview_job_id: 0,
            list_preview_job_epoch: std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0)),
            list_preview_partial_ready: false,
            list_preview_pending_path: None,
            list_play_pending: false,
            list_preview_prefetch_tx: None,
            list_preview_prefetch_rx: None,
            list_preview_prefetch_inflight: HashSet::new(),
            list_preview_cache: HashMap::new(),
            list_preview_cache_order: VecDeque::new(),
            plugin_search_paths: Self::default_plugin_search_paths(),
            plugin_search_path_input: String::new(),
            plugin_catalog: Vec::new(),
            plugin_scan_state: None,
            plugin_scan_error: None,
            plugin_probe_state: None,
            plugin_process_state: None,
            plugin_gui_state: None,
            plugin_job_id: 0,
            plugin_temp_seq: 0,
            zoo_enabled: false,
            zoo_walk_enabled: true,
            zoo_voice_enabled: false,
            zoo_use_bpm: true,
            zoo_gif_path: None,
            zoo_voice_path: None,
            zoo_scale: 1.0,
            zoo_opacity: 1.0,
            zoo_speed: 140.0,
            zoo_flip_manual: false,
            zoo_anim_clock: 0.0,
            zoo_pos_x: 0.0,
            zoo_dir: 1.0,
            zoo_last_tick: std::time::Instant::now(),
            zoo_squish_until: None,
            zoo_last_error: None,
            zoo_texture_gen: 0,
            zoo_frames_raw: Vec::new(),
            zoo_frames_tex: Vec::new(),
            zoo_voice_cache_path: None,
            zoo_voice_cache: None,
            zoo_voice_audio: None,
            editor_apply_state: None,
            editor_decode_state: None,
            editor_decode_job_id: 0,
            edited_cache: HashMap::new(),
            export_state: None,
            csv_export_state: None,
            playing_path: None,

            export_cfg: ExportConfig {
                first_prompt: true,
                save_mode: SaveMode::NewFile,
                dest_folder: None,
                name_template: "{name} (gain{gain:+.1}dB)".into(),
                format_override: None,
                conflict: ConflictPolicy::Rename,
                backup_bak: true,
                export_srt: false,
            },
            show_export_settings: false,
            show_transcription_settings: false,
            show_first_save_prompt: false,
            project_path: None,
            project_open_pending: None,
            project_open_state: None,
            theme_mode: ThemeMode::Dark,
            item_bg_mode: ItemBgMode::Standard,
            show_rename_dialog: false,
            rename_target: None,
            rename_input: String::new(),
            rename_focus_next: false,
            rename_error: None,
            show_batch_rename_dialog: false,
            batch_rename_targets: Vec::new(),
            batch_rename_pattern: "{name}_{n}".into(),
            batch_rename_start: 1,
            batch_rename_pad: 2,
            batch_rename_error: None,
            saving_sources: Vec::new(),
            saving_virtual: Vec::new(),
            saving_format_targets: Vec::new(),
            saving_edit_sources: Vec::new(),
            saving_mode: None,
            overwrite_undo_stack: Vec::new(),

            lufs_override: HashMap::new(),
            lufs_recalc_deadline: HashMap::new(),
            lufs_rx2: None,
            lufs_worker_busy: false,
            sample_rate_override: HashMap::new(),
            sample_rate_probe_cache: HashMap::new(),
            bit_depth_override: HashMap::new(),
            format_override: HashMap::new(),
            src_quality: SrcQuality::Good,
            show_resample_dialog: false,
            resample_targets: Vec::new(),
            resample_target_sr: 48_000,
            resample_error: None,
            bulk_resample_state: None,
            leave_intent: None,
            show_leave_prompt: false,
            pending_activate_path: None,
            pending_activate_kind: None,
            pending_activate_ready: false,
            heavy_preview_rx: None,
            heavy_preview_gen_counter: 0,
            heavy_preview_expected_gen: 0,
            heavy_preview_expected_path: None,
            heavy_preview_expected_tool: None,
            heavy_overlay_rx: None,
            overlay_gen_counter: 0,
            overlay_expected_gen: 0,
            overlay_expected_path: None,
            overlay_expected_tool: None,

            startup: startup_state,
            pending_screenshot: None,
            exit_after_screenshot: false,
            screenshot_seq: 0,

            debug: debug_state,
            debug_summary_seq: 0,
            ipc_rx,
            mcp_cmd_rx: None,
            mcp_resp_tx: None,
            #[cfg(feature = "kittest")]
            test_dialogs: TestDialogQueue::default(),
        };
        app.load_prefs();
        app.refresh_audio_output_devices();
        if app.audio_output_device_name.is_some() {
            let preferred = app.audio_output_device_name.clone();
            let _ = app.apply_audio_output_device_selection(preferred, false);
        }
        app.refresh_transcript_ai_status();
        app.refresh_music_ai_status();
        app.reload_zoo_gif_frames();
        app.load_tools_config();
        app.load_effect_graph_library();
        app.revalidate_effect_graph_draft();
        app.apply_startup_paths();
        app.setup_debug_automation();
        app.setup_mcp_server(&startup);
        app
    }
}
