//! The third-party licence snapshot behind Help -> Licenses.
//!
//! The data is generated by `commands/generate_licenses.ps1` and committed, so
//! the binary carries every licence text it is obliged to show without needing
//! the network at build time or at runtime.
//!
//! Licence texts are pooled: 640 crates share 330 distinct texts, because a
//! permissive licence carries a different copyright line for each holder.
//! Components reference the pool by key rather than repeating the text, which
//! is what keeps the embedded snapshot near a megabyte instead of four.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

const SNAPSHOT: &str = include_str!("../../assets/licenses/third_party.json");

/// How urgently a component wants the reader's attention.
///
/// Anything that is not `None` is repeated in the window's summary section, so
/// the handful of entries with real obligations are not lost among six hundred
/// uneventful MIT crates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Flag {
    /// Worth knowing about when distributing, but nothing to obtain first.
    Notice,
    /// Needs a decision or a licence before commercial distribution.
    Caution,
}

impl Flag {
    fn parse(raw: Option<&str>) -> Option<Self> {
        match raw {
            Some("caution") => Some(Flag::Caution),
            Some("notice") => Some(Flag::Notice),
            _ => None,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Flag::Caution => "CAUTION",
            Flag::Notice => "NOTICE",
        }
    }
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    generated_at: String,
    licenses: Vec<PooledLicense>,
    components: Vec<RawComponent>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PooledLicense {
    pub key: String,
    pub id: String,
    pub name: String,
    pub text: String,
}

#[derive(Debug, Deserialize)]
struct RawComponent {
    name: String,
    version: String,
    kind: String,
    license_expr: String,
    license_ids: Vec<String>,
    license_keys: Vec<String>,
    authors: String,
    repository: String,
    flag: Option<String>,
    note: Option<String>,
    #[serde(default)]
    topic: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Component {
    pub name: String,
    pub version: String,
    pub kind: String,
    pub license_expr: String,
    pub license_ids: Vec<String>,
    pub license_keys: Vec<String>,
    pub authors: String,
    pub repository: String,
    pub flag: Option<Flag>,
    pub note: Option<String>,
    /// Groups entries that are all one issue -- a wrapper crate, its `-sys`
    /// crate and the C library they build -- so the summary says it once.
    pub topic: Option<String>,
    /// Lowercased `name + version + licence + authors`, so the search box can
    /// filter six hundred rows per keystroke without allocating.
    haystack: String,
}

impl Component {
    /// Case-insensitive substring match across name, version, licence and
    /// authors. Deliberately not a regex: this is a "where is that crate"
    /// box, and a stray `(` in a licence expression should not error.
    pub fn matches(&self, needle_lowercase: &str) -> bool {
        needle_lowercase.is_empty() || self.haystack.contains(needle_lowercase)
    }
}

/// One issue in the summary: the entry that explains it, plus the other
/// components it covers.
pub struct FlaggedTopic<'a> {
    pub primary: &'a Component,
    pub also: Vec<&'a Component>,
}

pub struct Manifest {
    pub generated_at: String,
    pub components: Vec<Component>,
    licenses: Vec<PooledLicense>,
    by_key: HashMap<String, usize>,
}

impl Manifest {
    pub fn license(&self, key: &str) -> Option<&PooledLicense> {
        self.by_key.get(key).map(|idx| &self.licenses[*idx])
    }

    /// How many components carry a flag, before topic grouping folds the
    /// duplicates together.
    pub fn flagged_count(&self) -> usize {
        self.components.iter().filter(|c| c.flag.is_some()).count()
    }

    /// The flagged components collapsed by topic, for the summary section.
    ///
    /// One AAC problem spread across `fdk-aac`, `fdk-aac-sys` and the
    /// Fraunhofer sources they compile is one thing to know, not three. The
    /// authoritative entry leads -- components are stored kind-first, so the
    /// bundled C library outranks the crates wrapping it -- and the rest are
    /// named alongside it. Untopiced entries stand alone.
    pub fn flagged_topics(&self) -> Vec<FlaggedTopic<'_>> {
        let mut topics: Vec<FlaggedTopic<'_>> = Vec::new();
        for component in self.components.iter().filter(|c| c.flag.is_some()) {
            let existing = component.topic.as_ref().and_then(|topic| {
                topics
                    .iter_mut()
                    .find(|t| t.primary.topic.as_ref() == Some(topic))
            });
            match existing {
                Some(group) => group.also.push(component),
                None => topics.push(FlaggedTopic {
                    primary: component,
                    also: Vec::new(),
                }),
            }
        }
        topics.sort_by(|a, b| {
            b.primary.flag.cmp(&a.primary.flag).then_with(|| {
                a.primary
                    .name
                    .to_lowercase()
                    .cmp(&b.primary.name.to_lowercase())
            })
        });
        topics
    }

    /// Every SPDX id in the snapshot with how many components carry it,
    /// commonest first.
    ///
    /// This is the "what am I actually shipping" answer, and it is the line a
    /// reader scans before anything else: six hundred MIT crates are not news,
    /// one LGPL entry is.
    pub fn license_id_counts(&self) -> Vec<(&str, usize)> {
        let mut counts: HashMap<&str, usize> = HashMap::new();
        for component in &self.components {
            for id in &component.license_ids {
                *counts.entry(id.as_str()).or_default() += 1;
            }
        }
        let mut counts: Vec<(&str, usize)> = counts.into_iter().collect();
        counts.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(b.0)));
        counts
    }

    /// The `kind` groups present, in the order the snapshot lists them.
    pub fn kinds(&self) -> Vec<&str> {
        let mut kinds: Vec<&str> = Vec::new();
        for component in &self.components {
            if !kinds.contains(&component.kind.as_str()) {
                kinds.push(component.kind.as_str());
            }
        }
        kinds
    }
}

/// Human-readable heading for a `kind` group.
pub fn kind_title(kind: &str) -> &str {
    match kind {
        "bundled-native" => "Bundled native code (compiled into the binary)",
        "runtime-dll" => "Redistributed binaries (copied by the installer)",
        "spec" => "Interfaces and trademarks",
        "font" => "Fonts",
        "data" => "Embedded data",
        "model" => "Machine-learning models (downloaded at runtime)",
        "crate" => "Rust crates",
        other => other,
    }
}

/// Parses the embedded snapshot once, on first open of the window.
///
/// Parsing a megabyte of JSON is not something startup should pay for when
/// most sessions never open the Licenses window.
pub fn manifest() -> &'static Manifest {
    static MANIFEST: OnceLock<Manifest> = OnceLock::new();
    MANIFEST.get_or_init(|| {
        let raw: RawManifest = serde_json::from_str(SNAPSHOT)
            .expect("assets/licenses/third_party.json is malformed; regenerate it with commands/generate_licenses.ps1");

        let by_key = raw
            .licenses
            .iter()
            .enumerate()
            .map(|(idx, license)| (license.key.clone(), idx))
            .collect();

        let components = raw
            .components
            .into_iter()
            .map(|c| {
                let haystack = format!(
                    "{} {} {} {} {}",
                    c.name, c.version, c.license_expr, c.authors, c.kind
                )
                .to_lowercase();
                Component {
                    name: c.name,
                    version: c.version,
                    kind: c.kind,
                    license_expr: c.license_expr,
                    license_ids: c.license_ids,
                    license_keys: c.license_keys,
                    authors: c.authors,
                    repository: c.repository,
                    flag: Flag::parse(c.flag.as_deref()),
                    note: c.note,
                    topic: c.topic,
                    haystack,
                }
            })
            .collect();

        Manifest {
            generated_at: raw.generated_at,
            components,
            licenses: raw.licenses,
            by_key,
        }
    })
}

/// The whole snapshot as plain text, for the window's "Copy all" button.
///
/// Written to be pasteable straight into a NOTICES file that ships with a
/// build, which is the form most distribution channels ask for.
pub fn plain_text() -> String {
    let manifest = manifest();
    let mut out = String::with_capacity(1 << 20);

    out.push_str("NeoWaves Audio List Editor -- third-party licences\n");
    out.push_str(&format!("Snapshot generated {}\n", manifest.generated_at));
    out.push_str(&format!("{} components\n\n", manifest.components.len()));

    out.push_str("== Licences in this build ==\n\n");
    for (id, count) in manifest.license_id_counts() {
        out.push_str(&format!("  {id} x{count}\n"));
    }
    out.push('\n');

    let topics = manifest.flagged_topics();
    if !topics.is_empty() {
        out.push_str("== Commercial distribution notes ==\n\n");
        for topic in topics {
            let flag = topic.primary.flag.map(Flag::label).unwrap_or_default();
            out.push_str(&format!("[{}] {}\n", flag, topic.primary.name));
            if let Some(note) = &topic.primary.note {
                out.push_str(&format!("    {note}\n"));
            }
            if !topic.also.is_empty() {
                let names: Vec<&str> = topic.also.iter().map(|c| c.name.as_str()).collect();
                out.push_str(&format!("    Also covers: {}\n", names.join(", ")));
            }
            out.push('\n');
        }
    }

    for kind in manifest.kinds() {
        out.push_str(&format!("\n== {} ==\n\n", kind_title(kind)));
        for component in manifest.components.iter().filter(|c| c.kind == kind) {
            out.push_str(&format!(
                "{} {} -- {}\n",
                component.name, component.version, component.license_expr
            ));
            if !component.authors.is_empty() {
                out.push_str(&format!("    {}\n", component.authors));
            }
            if !component.repository.is_empty() {
                out.push_str(&format!("    {}\n", component.repository));
            }
        }
    }

    out.push_str("\n\n== Licence texts ==\n");
    for license in &manifest.licenses {
        out.push_str(&format!("\n--- {} ({}) ---\n\n", license.name, license.key));
        out.push_str(&license.text);
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The snapshot is generated out-of-band and committed, so the only thing
    /// standing between a botched regeneration and a release is this test.
    #[test]
    fn snapshot_parses() {
        let manifest = manifest();
        assert!(
            manifest.components.len() > 100,
            "expected the full dependency graph, got {} components",
            manifest.components.len()
        );
    }

    #[test]
    fn every_component_resolves_its_licence_text() {
        let manifest = manifest();
        for component in &manifest.components {
            for key in &component.license_keys {
                let license = manifest.license(key).unwrap_or_else(|| {
                    panic!("{} references unknown licence key {key}", component.name)
                });
                assert!(
                    !license.text.trim().is_empty(),
                    "{} references licence {key}, which has no text",
                    component.name
                );
            }
        }
    }

    /// A crate without a licence text is a crate whose copyright notice we are
    /// failing to reproduce. The zoo assets are the one known gap and are
    /// flagged as such in extra.json.
    #[test]
    fn only_known_components_lack_licence_text() {
        let manifest = manifest();
        let missing: Vec<&str> = manifest
            .components
            .iter()
            .filter(|c| c.license_keys.is_empty())
            .map(|c| c.name.as_str())
            .collect();
        assert_eq!(
            missing,
            vec!["Zoo default assets (default.gif / default.wav)"],
            "a component lost its licence text"
        );
    }

    #[test]
    fn known_dependencies_are_present() {
        let manifest = manifest();
        for expected in [
            "eframe",
            "symphonia",
            "openh264",
            "mp3lame-encoder",
            "fdk-aac",
            "Cisco OpenH264",
            "Fraunhofer FDK AAC Codec Library",
            "LAME (libmp3lame)",
            "Noto Sans JP",
        ] {
            assert!(
                manifest.components.iter().any(|c| c.name == expected),
                "{expected} is missing from the licence snapshot"
            );
        }
    }

    /// The three dependencies that need action before commercial distribution
    /// must keep saying so. If a future edit drops one of these notes, the
    /// window silently stops warning about it.
    #[test]
    fn commercial_cautions_survive() {
        let manifest = manifest();
        let cautions: Vec<&str> = manifest
            .components
            .iter()
            .filter(|c| c.flag == Some(Flag::Caution))
            .map(|c| c.name.as_str())
            .collect();
        for expected in [
            "Cisco OpenH264",
            "Fraunhofer FDK AAC Codec Library",
            "LAME (libmp3lame)",
        ] {
            assert!(
                cautions.contains(&expected),
                "{expected} lost its caution flag"
            );
        }
        assert!(
            manifest
                .components
                .iter()
                .filter(|c| c.flag == Some(Flag::Caution))
                .all(|c| c.note.is_some()),
            "a caution without an explanation is not much of a warning"
        );
    }

    /// Nothing in the graph may be strong copyleft. LGPL is present on purpose
    /// (LAME), and MPL is file-level, but a plain GPL or AGPL crate would make
    /// the whole binary undistributable under its current terms.
    #[test]
    fn no_strong_copyleft_crept_in() {
        let manifest = manifest();
        for component in &manifest.components {
            for id in &component.license_ids {
                let strong = (id.starts_with("GPL-") || id.starts_with("AGPL-"))
                    // GPL-3.0 is pooled only because LGPL-3.0 is written as a
                    // set of additional permissions on top of it, and the LAME
                    // entry cites both.
                    && component.name != "LAME (libmp3lame)";
                assert!(
                    !strong,
                    "{} is {id}: strong copyleft would relicense the whole binary",
                    component.name
                );
            }
        }
    }

    /// The summary exists to be scannable. One issue spread across a wrapper
    /// crate, its `-sys` crate and the C library must collapse to one row, and
    /// the row must be led by the entry that actually explains it.
    #[test]
    fn flagged_topics_collapse_to_one_row_each() {
        let manifest = manifest();
        let topics = manifest.flagged_topics();
        assert!(
            topics.len() < manifest.flagged_count(),
            "grouping did not collapse anything"
        );

        for (primary, expected_also) in [
            (
                "Fraunhofer FDK AAC Codec Library",
                vec!["fdk-aac", "fdk-aac-sys"],
            ),
            ("LAME (libmp3lame)", vec!["mp3lame-encoder", "mp3lame-sys"]),
            ("Cisco OpenH264", vec!["openh264", "openh264-sys2"]),
        ] {
            let topic = topics
                .iter()
                .find(|t| t.primary.name == primary)
                .unwrap_or_else(|| panic!("{primary} is not leading its own summary row"));
            let also: Vec<&str> = topic.also.iter().map(|c| c.name.as_str()).collect();
            assert_eq!(also, expected_also, "wrong members grouped under {primary}");
        }

        // Every flagged component reaches the summary exactly once.
        let reached: usize = topics.iter().map(|t| 1 + t.also.len()).sum();
        assert_eq!(reached, manifest.flagged_count());
    }

    #[test]
    fn license_breakdown_is_ordered_and_complete() {
        let manifest = manifest();
        let counts = manifest.license_id_counts();
        assert!(
            counts.windows(2).all(|w| w[0].1 >= w[1].1),
            "not sorted by count"
        );
        let total: usize = counts.iter().map(|(_, n)| n).sum();
        let expected: usize = manifest
            .components
            .iter()
            .map(|c| c.license_ids.len())
            .sum();
        assert_eq!(total, expected);
        assert_eq!(
            counts.first().map(|(id, _)| *id),
            Some("MIT"),
            "MIT should dominate a Rust dependency graph"
        );
    }

    #[test]
    fn search_matches_name_and_licence() {
        let manifest = manifest();
        let symphonia = manifest
            .components
            .iter()
            .find(|c| c.name == "symphonia")
            .expect("symphonia present");
        assert!(symphonia.matches("mpl"));
        assert!(symphonia.matches("SYMPHONIA".to_lowercase().as_str()));
        assert!(!symphonia.matches("definitely-not-here"));
        assert!(symphonia.matches(""), "an empty query matches everything");
    }

    #[test]
    fn plain_text_carries_the_texts() {
        let text = plain_text();
        assert!(text.contains("Commercial distribution notes"));
        assert!(text.contains("NO PATENT LICENSE") || text.contains("NO EXPRESS OR IMPLIED"));
        assert!(text.contains("GNU LESSER GENERAL PUBLIC LICENSE"));
    }
}
