//! The third-party licence snapshot behind Help -> Licenses.
//!
//! The data is generated by `commands/generate_licenses.ps1` and committed, so
//! the binary carries every licence text it is obliged to show without needing
//! the network at build time or at runtime.
//!
//! Licence texts are pooled: 640 crates share 330 distinct texts, because a
//! permissive licence carries a different copyright line for each holder.
//! Components reference the pool by key rather than repeating the text, which
//! is what keeps the embedded snapshot near a megabyte instead of four.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

const SNAPSHOT: &str = include_str!("../../assets/licenses/third_party.json");

/// How urgently a component wants the reader's attention.
///
/// Anything that is not `None` is repeated in the window's summary section, so
/// the handful of entries with real obligations are not lost among six hundred
/// uneventful MIT crates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Flag {
    /// Worth knowing about when distributing, but nothing to obtain first.
    Notice,
    /// Needs a decision or a licence before commercial distribution.
    Caution,
}

impl Flag {
    fn parse(raw: Option<&str>) -> Option<Self> {
        match raw {
            Some("caution") => Some(Flag::Caution),
            Some("notice") => Some(Flag::Notice),
            _ => None,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Flag::Caution => "CAUTION",
            Flag::Notice => "NOTICE",
        }
    }
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    generated_at: String,
    licenses: Vec<PooledLicense>,
    components: Vec<RawComponent>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PooledLicense {
    pub key: String,
    pub id: String,
    pub name: String,
    pub text: String,
}

#[derive(Debug, Deserialize)]
struct RawComponent {
    name: String,
    version: String,
    kind: String,
    license_expr: String,
    license_ids: Vec<String>,
    license_keys: Vec<String>,
    authors: String,
    repository: String,
    flag: Option<String>,
    note: Option<String>,
    #[serde(default)]
    topic: Option<String>,
    #[serde(default)]
    feature: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Component {
    pub name: String,
    pub version: String,
    pub kind: String,
    pub license_expr: String,
    pub license_ids: Vec<String>,
    pub license_keys: Vec<String>,
    pub authors: String,
    pub repository: String,
    pub flag: Option<Flag>,
    pub note: Option<String>,
    /// Groups entries that are all one issue — a wrapper crate, its `-sys`
    /// crate and the C library they build — so the summary says it once.
    pub topic: Option<String>,
    /// The cargo feature gating this component, if any.
    pub feature: Option<String>,
    /// Whether that feature is compiled into *this* binary. `true` for
    /// everything unconditional.
    pub active: bool,
    /// Lowercased `name + version + licence + authors`, so the search box can
    /// filter six hundred rows per keystroke without allocating.
    haystack: String,
}

impl Component {
    /// Case-insensitive substring match across name, version, licence and
    /// authors. Deliberately not a regex: this is a "where is that crate"
    /// box, and a stray `(` in a licence expression should not error.
    pub fn matches(&self, needle_lowercase: &str) -> bool {
        needle_lowercase.is_empty() || self.haystack.contains(needle_lowercase)
    }
}

/// One issue in the summary: the entry that explains it, plus the other
/// components it covers.
pub struct FlaggedTopic<'a> {
    pub primary: &'a Component,
    pub also: Vec<&'a Component>,
}

pub struct Manifest {
    pub generated_at: String,
    pub components: Vec<Component>,
    licenses: Vec<PooledLicense>,
    by_key: HashMap<String, usize>,
}

impl Manifest {
    pub fn license(&self, key: &str) -> Option<&PooledLicense> {
        self.by_key.get(key).map(|idx| &self.licenses[*idx])
    }

    /// How many components carry a flag *and* are compiled into this binary,
    /// before topic grouping folds the duplicates together.
    pub fn flagged_count(&self) -> usize {
        self.components
            .iter()
            .filter(|c| c.flag.is_some() && c.active)
            .count()
    }

    /// The optional components this build did and did not compile in.
    ///
    /// Returned in snapshot order, which puts the bundled native code and the
    /// VST 3 entry ahead of the crates that wrap them, so the names a reader
    /// recognises come first.
    pub fn build_contents(&self) -> (Vec<&Component>, Vec<&Component>) {
        let mut included = Vec::new();
        let mut excluded = Vec::new();
        for component in self.components.iter().filter(|c| c.feature.is_some()) {
            // One row per feature: the first component carrying it is the
            // authoritative one, and its wrapper crates would only repeat it.
            let already = |seen: &Vec<&Component>| {
                seen.iter()
                    .any(|c: &&Component| c.feature == component.feature)
            };
            if component.active {
                if !already(&included) {
                    included.push(component);
                }
            } else if !already(&excluded) {
                excluded.push(component);
            }
        }
        (included, excluded)
    }

    /// The flagged components collapsed by topic, for the summary section.
    ///
    /// One AAC problem spread across `fdk-aac`, `fdk-aac-sys` and the
    /// Fraunhofer sources they compile is one thing to know, not three. The
    /// authoritative entry leads — components are stored kind-first, so the
    /// bundled C library outranks the crates wrapping it — and the rest are
    /// named alongside it. Untopiced entries stand alone.
    pub fn flagged_topics(&self) -> Vec<FlaggedTopic<'_>> {
        let mut topics: Vec<FlaggedTopic<'_>> = Vec::new();
        for component in self
            .components
            .iter()
            .filter(|c| c.flag.is_some() && c.active)
        {
            let existing = component.topic.as_ref().and_then(|topic| {
                topics
                    .iter_mut()
                    .find(|t| t.primary.topic.as_ref() == Some(topic))
            });
            match existing {
                Some(group) => group.also.push(component),
                None => topics.push(FlaggedTopic {
                    primary: component,
                    also: Vec::new(),
                }),
            }
        }
        topics.sort_by(|a, b| {
            b.primary.flag.cmp(&a.primary.flag).then_with(|| {
                a.primary
                    .name
                    .to_lowercase()
                    .cmp(&b.primary.name.to_lowercase())
            })
        });
        topics
    }

    /// Every SPDX id in the snapshot with how many components carry it,
    /// commonest first.
    ///
    /// This is the "what am I actually shipping" answer, and it is the line a
    /// reader scans before anything else: six hundred MIT crates are not news,
    /// one LGPL entry is.
    pub fn license_id_counts(&self) -> Vec<(&str, usize)> {
        let mut counts: HashMap<&str, usize> = HashMap::new();
        for component in self.components.iter().filter(|c| c.active) {
            for id in &component.license_ids {
                *counts.entry(id.as_str()).or_default() += 1;
            }
        }
        let mut counts: Vec<(&str, usize)> = counts.into_iter().collect();
        counts.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(b.0)));
        counts
    }

    /// NeoWaves's own statement about what a build of it may be used for.
    ///
    /// Not a third-party component, so it is kept out of the tables below and
    /// given its own block at the top of the window.
    pub fn distribution_terms(&self) -> Option<&Component> {
        self.components.iter().find(|c| c.kind == "distribution")
    }

    /// The `kind` groups present, in the order the snapshot lists them.
    pub fn kinds(&self) -> Vec<&str> {
        let mut kinds: Vec<&str> = Vec::new();
        for component in self.components.iter().filter(|c| c.kind != "distribution") {
            if !kinds.contains(&component.kind.as_str()) {
                kinds.push(component.kind.as_str());
            }
        }
        kinds
    }
}

/// Whether a cargo feature named in the snapshot is compiled into this binary.
///
/// The snapshot is generated once against the widest feature set the project
/// supports, so it lists components a given build may not contain. Resolving
/// the name here with `cfg!` is what lets the window describe the binary in
/// front of the reader instead of the repository — and, more to the point,
/// stops it claiming obligations for code that was never linked in.
///
/// `None` means the snapshot named a feature this table does not know, which
/// is a bug in `extra.json`; `encumbered_components_declare_a_known_feature`
/// fails on it.
pub fn feature_active(name: &str) -> Option<bool> {
    match name {
        "video" => Some(cfg!(feature = "video")),
        "aac_fdk" => Some(cfg!(feature = "aac_fdk")),
        "mp3_lame" => Some(cfg!(feature = "mp3_lame")),
        "plugin_native_vst3" => Some(cfg!(feature = "plugin_native_vst3")),
        "plugin_native_clap" => Some(cfg!(feature = "plugin_native_clap")),
        _ => None,
    }
}

/// Human-readable heading for a `kind` group.
pub fn kind_title(kind: &str) -> &str {
    match kind {
        "distribution" => "About this distribution",
        "bundled-native" => "Bundled native code (compiled into the binary)",
        "runtime-dll" => "Redistributed binaries (copied by the installer)",
        "spec" => "Interfaces and trademarks",
        "font" => "Fonts",
        "data" => "Embedded data",
        "model" => "Machine-learning models (downloaded at runtime)",
        "crate" => "Rust crates",
        other => other,
    }
}

/// Parses the embedded snapshot once, on first open of the window.
///
/// Parsing a megabyte of JSON is not something startup should pay for when
/// most sessions never open the Licenses window.
pub fn manifest() -> &'static Manifest {
    static MANIFEST: OnceLock<Manifest> = OnceLock::new();
    MANIFEST.get_or_init(|| {
        let raw: RawManifest = serde_json::from_str(SNAPSHOT)
            .expect("assets/licenses/third_party.json is malformed; regenerate it with commands/generate_licenses.ps1");

        let by_key = raw
            .licenses
            .iter()
            .enumerate()
            .map(|(idx, license)| (license.key.clone(), idx))
            .collect();

        let components = raw
            .components
            .into_iter()
            .map(|c| {
                let haystack = format!(
                    "{} {} {} {} {}",
                    c.name, c.version, c.license_expr, c.authors, c.kind
                )
                .to_lowercase();
                Component {
                    name: c.name,
                    version: c.version,
                    kind: c.kind,
                    license_expr: c.license_expr,
                    license_ids: c.license_ids,
                    license_keys: c.license_keys,
                    authors: c.authors,
                    repository: c.repository,
                    flag: Flag::parse(c.flag.as_deref()),
                    note: c.note,
                    active: c
                        .feature
                        .as_deref()
                        .map(|f| feature_active(f).unwrap_or(true))
                        .unwrap_or(true),
                    feature: c.feature,
                    topic: c.topic,
                    haystack,
                }
            })
            .collect();

        Manifest {
            generated_at: raw.generated_at,
            components,
            licenses: raw.licenses,
            by_key,
        }
    })
}

/// The whole snapshot as plain text, for the window's "Copy all" button.
///
/// Written to be pasteable straight into a NOTICES file that ships with a
/// build, which is the form most distribution channels ask for.
pub fn plain_text() -> String {
    let manifest = manifest();
    let mut out = String::with_capacity(1 << 20);

    out.push_str("NeoWaves Audio List Editor -- third-party licences\n");
    out.push_str(&format!("Snapshot generated {}\n", manifest.generated_at));
    out.push_str(&format!("{} components\n\n", manifest.components.len()));

    if let Some(terms) = manifest.distribution_terms() {
        out.push_str("== About this distribution ==\n\n");
        if let Some(note) = &terms.note {
            out.push_str(&format!("{note}\n\n"));
        }
        for key in &terms.license_keys {
            if let Some(license) = manifest.license(key) {
                out.push_str(&license.text);
                out.push_str("\n\n");
            }
        }
    }

    let (included, excluded) = manifest.build_contents();
    out.push_str("== Optional components in this build ==\n\n");
    for component in &included {
        out.push_str(&format!("  [x] {}\n", component.name));
    }
    for component in &excluded {
        out.push_str(&format!("  [ ] {} (not in this build)\n", component.name));
    }
    out.push('\n');

    out.push_str("== Licences in this build ==\n\n");
    for (id, count) in manifest.license_id_counts() {
        out.push_str(&format!("  {id} x{count}\n"));
    }
    out.push('\n');

    let topics = manifest.flagged_topics();
    if !topics.is_empty() {
        out.push_str("== Commercial distribution notes ==\n\n");
        for topic in topics {
            let flag = topic.primary.flag.map(Flag::label).unwrap_or_default();
            out.push_str(&format!("[{}] {}\n", flag, topic.primary.name));
            if let Some(note) = &topic.primary.note {
                out.push_str(&format!("    {note}\n"));
            }
            if !topic.also.is_empty() {
                let names: Vec<&str> = topic.also.iter().map(|c| c.name.as_str()).collect();
                out.push_str(&format!("    Also covers: {}\n", names.join(", ")));
            }
            out.push('\n');
        }
    }

    for kind in manifest.kinds() {
        out.push_str(&format!("\n== {} ==\n\n", kind_title(kind)));
        for component in manifest
            .components
            .iter()
            .filter(|c| c.kind == kind && c.active)
        {
            out.push_str(&format!(
                "{} {} -- {}\n",
                component.name, component.version, component.license_expr
            ));
            if !component.authors.is_empty() {
                out.push_str(&format!("    {}\n", component.authors));
            }
            if !component.repository.is_empty() {
                out.push_str(&format!("    {}\n", component.repository));
            }
        }
    }

    out.push_str("\n\n== Licence texts ==\n");
    for license in &manifest.licenses {
        out.push_str(&format!("\n--- {} ({}) ---\n\n", license.name, license.key));
        out.push_str(&license.text);
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The snapshot is generated out-of-band and committed, so the only thing
    /// standing between a botched regeneration and a release is this test.
    #[test]
    fn snapshot_parses() {
        let manifest = manifest();
        assert!(
            manifest.components.len() > 100,
            "expected the full dependency graph, got {} components",
            manifest.components.len()
        );
    }

    #[test]
    fn every_component_resolves_its_licence_text() {
        let manifest = manifest();
        for component in &manifest.components {
            for key in &component.license_keys {
                let license = manifest.license(key).unwrap_or_else(|| {
                    panic!("{} references unknown licence key {key}", component.name)
                });
                assert!(
                    !license.text.trim().is_empty(),
                    "{} references licence {key}, which has no text",
                    component.name
                );
            }
        }
    }

    /// A component without a licence text is one whose copyright notice this
    /// binary is failing to reproduce. There is no longer any exception: the
    /// zoo assets were the last gap and are now MIT like the rest of the
    /// project, so the bar is simply "every component, no exceptions".
    #[test]
    fn every_component_has_licence_text() {
        let manifest = manifest();
        let missing: Vec<&str> = manifest
            .components
            .iter()
            .filter(|c| c.license_keys.is_empty())
            .map(|c| c.name.as_str())
            .collect();
        assert!(
            missing.is_empty(),
            "these components ship with no licence text: {missing:?}"
        );
    }

    /// Every native dependency is statically linked -- ONNX Runtime through
    /// `ort`, and Oniguruma, LAME, the FDK and SQLite through `-sys` crates
    /// that compile their C with `cc`. The installer copies no codec or
    /// runtime DLL, so nothing may claim to be a redistributed one: saying so
    /// would describe an obligation that does not exist and hide the real one,
    /// which is that the code is inside the executable.
    #[test]
    fn nothing_claims_to_be_a_redistributed_dll() {
        let manifest = manifest();
        let claimed: Vec<&str> = manifest
            .components
            .iter()
            .filter(|c| c.kind == "runtime-dll")
            .map(|c| c.name.as_str())
            .collect();
        assert!(
            claimed.is_empty(),
            "these claim to be shipped as separate DLLs, but everything is \
             statically linked: {claimed:?}"
        );
        // The two that used to be filed that way must still be listed, just in
        // the category that matches how they actually reach the binary.
        for name in ["ONNX Runtime", "Oniguruma"] {
            let component = manifest
                .components
                .iter()
                .find(|c| c.name == name)
                .unwrap_or_else(|| panic!("{name} disappeared from the snapshot"));
            assert_eq!(
                component.kind, "bundled-native",
                "{name} is statically linked and should be filed as bundled native code"
            );
        }
    }

    #[test]
    fn known_dependencies_are_present() {
        let manifest = manifest();
        for expected in [
            "eframe",
            "symphonia",
            "openh264",
            "mp3lame-encoder",
            "fdk-aac",
            "Cisco OpenH264",
            "Fraunhofer FDK AAC Codec Library",
            "LAME (libmp3lame)",
            "Noto Sans JP",
        ] {
            assert!(
                manifest.components.iter().any(|c| c.name == expected),
                "{expected} is missing from the licence snapshot"
            );
        }
    }

    /// Every flag still has to explain itself, whatever its level.
    #[test]
    fn flags_are_explained() {
        let manifest = manifest();
        for component in manifest.components.iter().filter(|c| c.flag.is_some()) {
            assert!(
                component.note.is_some(),
                "{} carries a flag with no explanation",
                component.name
            );
        }
    }

    /// The four entries that used to need action before distribution are now
    /// resolved, and each still says so. If a future edit drops one of these
    /// notes the window silently stops explaining a real obligation.
    #[test]
    fn the_resolved_obligations_still_explain_themselves() {
        let manifest = manifest();
        for (name, must_mention) in [
            ("Cisco OpenH264", "NOT IN THE DEFAULT BUILD"),
            ("Fraunhofer FDK AAC Codec Library", "GPL-incompatible"),
            ("LAME (libmp3lame)", "section 4"),
            ("Steinberg VST 3 interface", "MIT"),
            ("NeoWaves distribution terms", "LGPL-3.0"),
        ] {
            let component = manifest
                .components
                .iter()
                .find(|c| c.name == name)
                .unwrap_or_else(|| panic!("{name} disappeared from the snapshot"));
            let note = component.note.as_deref().unwrap_or("");
            assert!(
                note.contains(must_mention),
                "{name}'s note no longer mentions {must_mention:?}"
            );
        }
    }

    /// The project's own terms lead the window and must not be mixed in with
    /// the third-party components, where they would sort alphabetically into
    /// the middle of the notes.
    #[test]
    fn distribution_terms_lead_and_stay_out_of_the_tables() {
        let manifest = manifest();
        let terms = manifest
            .distribution_terms()
            .expect("the distribution terms went missing");
        assert!(terms.note.is_some());
        assert!(
            !terms.license_keys.is_empty(),
            "the terms should carry their full text"
        );
        assert!(
            !manifest.kinds().contains(&"distribution"),
            "the terms must not appear as a component group"
        );
        assert!(
            !manifest
                .flagged_topics()
                .iter()
                .any(|t| t.primary.kind == "distribution"),
            "the terms have their own block, not a row in the notes"
        );
        assert!(plain_text().contains("About this distribution"));
    }

    /// The FDK AAC licence is GPL-incompatible: FFmpeg has to gate it behind
    /// `--enable-nonfree` for exactly this reason. Every GPL-or-not decision in
    /// this project was made to keep the two apart, so pin it here — adding a
    /// GPL dependency later would quietly make the AAC-enabled binary
    /// undistributable.
    #[test]
    fn fdk_aac_never_shares_a_binary_with_gpl() {
        let manifest = manifest();
        let has_fdk = manifest
            .components
            .iter()
            .any(|c| c.license_ids.iter().any(|id| id == "FDK-AAC"));
        if !has_fdk {
            return;
        }
        for component in &manifest.components {
            for id in &component.license_ids {
                // LGPL is fine, and GPL-3.0 is pooled only because LGPL-3.0 is
                // written as additional permissions on top of it.
                let is_gpl = (id.starts_with("GPL-") || id.starts_with("AGPL-"))
                    && component.name != "LAME (libmp3lame)";
                assert!(
                    !is_gpl,
                    "{} is {id}, which cannot share a binary with the FDK AAC codec",
                    component.name
                );
            }
        }
    }

    /// A `feature` in the snapshot that `feature_active` does not know would be
    /// silently treated as always-compiled-in, so the window would claim an
    /// obligation for code that is not there. Catch the typo at test time.
    #[test]
    fn gated_components_declare_a_known_feature() {
        let manifest = manifest();
        let mut seen = 0usize;
        for component in &manifest.components {
            let Some(feature) = component.feature.as_deref() else {
                continue;
            };
            seen += 1;
            assert!(
                feature_active(feature).is_some(),
                "{} is gated on unknown feature `{feature}`; add it to feature_active()",
                component.name
            );
        }
        assert!(
            seen >= 4,
            "expected the optional codecs to declare features"
        );
    }

    /// OpenH264 is off by default so the released binary carries no
    /// self-compiled H.264 codec. Under the default features it must land on
    /// the excluded side and stay out of the obligations summary.
    #[test]
    #[cfg(not(feature = "video"))]
    fn a_default_build_excludes_openh264() {
        let manifest = manifest();
        let (included, excluded) = manifest.build_contents();
        assert!(
            excluded.iter().any(|c| c.name == "Cisco OpenH264"),
            "OpenH264 should be listed as absent from a default build"
        );
        assert!(
            !included.iter().any(|c| c.name == "Cisco OpenH264"),
            "OpenH264 is not in a default build"
        );
        assert!(
            !manifest
                .flagged_topics()
                .iter()
                .any(|t| t.primary.name == "Cisco OpenH264"),
            "a component that was never linked in must not claim an obligation"
        );
        assert!(
            !plain_text().contains("openh264-sys2"),
            "the copyable notices should not list a crate this build never used"
        );
    }

    /// The mirror of the above: with `video` on, OpenH264 is really there and
    /// the page has to say so.
    #[test]
    #[cfg(feature = "video")]
    fn a_video_build_includes_openh264() {
        let manifest = manifest();
        let (included, _) = manifest.build_contents();
        assert!(included.iter().any(|c| c.name == "Cisco OpenH264"));
        assert!(manifest
            .flagged_topics()
            .iter()
            .any(|t| t.primary.name == "Cisco OpenH264"));
    }

    /// Nothing in the graph may be strong copyleft. LGPL is present on purpose
    /// (LAME), and MPL is file-level, but a plain GPL or AGPL crate would make
    /// the whole binary undistributable under its current terms.
    #[test]
    fn no_strong_copyleft_crept_in() {
        let manifest = manifest();
        for component in &manifest.components {
            for id in &component.license_ids {
                let strong = (id.starts_with("GPL-") || id.starts_with("AGPL-"))
                    // GPL-3.0 is pooled only because LGPL-3.0 is written as a
                    // set of additional permissions on top of it, and the LAME
                    // entry cites both.
                    && component.name != "LAME (libmp3lame)";
                assert!(
                    !strong,
                    "{} is {id}: strong copyleft would relicense the whole binary",
                    component.name
                );
            }
        }
    }

    /// The summary exists to be scannable. One issue spread across a wrapper
    /// crate, its `-sys` crate and the C library must collapse to one row, and
    /// the row must be led by the entry that actually explains it.
    #[test]
    fn flagged_topics_collapse_to_one_row_each() {
        let manifest = manifest();
        let topics = manifest.flagged_topics();
        assert!(
            topics.len() < manifest.flagged_count(),
            "grouping did not collapse anything"
        );

        // Each codec only leads a row in a build that actually contains it, so
        // the expectations follow the features rather than assuming a default
        // build.
        let mut expectations = Vec::new();
        if cfg!(feature = "aac_fdk") {
            expectations.push((
                "Fraunhofer FDK AAC Codec Library",
                vec!["fdk-aac", "fdk-aac-sys"],
            ));
        }
        if cfg!(feature = "mp3_lame") {
            expectations.push(("LAME (libmp3lame)", vec!["mp3lame-encoder", "mp3lame-sys"]));
        }
        if cfg!(feature = "video") {
            expectations.push(("Cisco OpenH264", vec!["openh264", "openh264-sys2"]));
        }
        for (primary, expected_also) in expectations {
            let topic = topics
                .iter()
                .find(|t| t.primary.name == primary)
                .unwrap_or_else(|| panic!("{primary} is not leading its own summary row"));
            let also: Vec<&str> = topic.also.iter().map(|c| c.name.as_str()).collect();
            assert_eq!(also, expected_also, "wrong members grouped under {primary}");
        }

        // Every flagged component that this build actually contains reaches the
        // summary exactly once.
        let reached: usize = topics.iter().map(|t| 1 + t.also.len()).sum();
        assert_eq!(reached, manifest.flagged_count());
    }

    #[test]
    fn license_breakdown_is_ordered_and_complete() {
        let manifest = manifest();
        let counts = manifest.license_id_counts();
        assert!(
            counts.windows(2).all(|w| w[0].1 >= w[1].1),
            "not sorted by count"
        );
        let total: usize = counts.iter().map(|(_, n)| n).sum();
        // Only what this build actually linked in is counted.
        let expected: usize = manifest
            .components
            .iter()
            .filter(|c| c.active)
            .map(|c| c.license_ids.len())
            .sum();
        assert_eq!(total, expected);
        assert_eq!(
            counts.first().map(|(id, _)| *id),
            Some("MIT"),
            "MIT should dominate a Rust dependency graph"
        );
    }

    #[test]
    fn search_matches_name_and_licence() {
        let manifest = manifest();
        let symphonia = manifest
            .components
            .iter()
            .find(|c| c.name == "symphonia")
            .expect("symphonia present");
        assert!(symphonia.matches("mpl"));
        assert!(symphonia.matches("SYMPHONIA".to_lowercase().as_str()));
        assert!(!symphonia.matches("definitely-not-here"));
        assert!(symphonia.matches(""), "an empty query matches everything");
    }

    #[test]
    fn plain_text_carries_the_texts() {
        let text = plain_text();
        assert!(text.contains("Commercial distribution notes"));
        assert!(text.contains("NO PATENT LICENSE") || text.contains("NO EXPRESS OR IMPLIED"));
        assert!(text.contains("GNU LESSER GENERAL PUBLIC LICENSE"));
    }
}
