use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};

use async_trait::async_trait;
use sha2::{Digest, Sha256};

use super::models::{
    AudioClassification, AudioContains, AudioEmbedding, AudioKind, InteractionInput,
    InteractionRequest, InteractionResponse, UcsAnalysis, UcsCandidate, UcsEntry, Usage,
    VoiceTranscript,
};
use super::provider::{AiError, AiProvider, ProviderCapabilities};

/// Deterministic provider used by UI/integration tests without credentials,
/// network access, persistent storage, or audio uploads.
pub struct MockAiProvider {
    next_interaction_id: AtomicU64,
    dimensions: usize,
}

impl Default for MockAiProvider {
    fn default() -> Self {
        Self {
            next_interaction_id: AtomicU64::new(1),
            dimensions: 8,
        }
    }
}

impl MockAiProvider {
    pub fn with_dimensions(dimensions: usize) -> Result<Self, AiError> {
        if !(1..=3_072).contains(&dimensions) {
            return Err(AiError::SchemaValidation(
                "mock embedding dimensions must be in 1..=3072".into(),
            ));
        }
        Ok(Self {
            next_interaction_id: AtomicU64::new(1),
            dimensions,
        })
    }

    fn embedding(&self, seed: &[u8], start_ms: u64, end_ms: u64) -> AudioEmbedding {
        let mut values = Vec::with_capacity(self.dimensions);
        let mut counter = 0u64;
        while values.len() < self.dimensions {
            let mut hasher = Sha256::new();
            hasher.update(seed);
            hasher.update(counter.to_le_bytes());
            for byte in hasher.finalize() {
                if values.len() == self.dimensions {
                    break;
                }
                values.push((f32::from(byte) - 127.5) / 127.5);
            }
            counter = counter.saturating_add(1);
        }
        let norm = values.iter().map(|value| value * value).sum::<f32>().sqrt();
        if norm > f32::EPSILON {
            for value in &mut values {
                *value /= norm;
            }
        }
        AudioEmbedding {
            model: "mock-embedding-v1".into(),
            dimensions: self.dimensions,
            values,
            segment_start_ms: start_ms,
            segment_end_ms: end_ms,
        }
    }
}

#[async_trait]
impl AiProvider for MockAiProvider {
    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities {
            provider_name: "mock".into(),
            interaction_model: "mock-interaction-v1".into(),
            embedding_model: Some("mock-embedding-v1".into()),
            supports_audio_understanding: true,
            supports_audio_embedding: true,
            supports_files_api: false,
            max_inline_bytes: usize::MAX,
            max_embedding_audio_seconds: u32::MAX,
            embedding_dimensions: self.dimensions,
        }
    }

    async fn interact(&self, request: InteractionRequest) -> Result<InteractionResponse, AiError> {
        let output_text = match request.input {
            InteractionInput::Text(text) => format!("Mock response: {}", text.trim()),
            InteractionInput::Content(values) => {
                format!("Mock received {} function result(s).", values.len())
            }
        };
        let input_tokens = output_text.split_whitespace().count() as u64;
        let output_tokens = input_tokens.saturating_add(1);
        Ok(InteractionResponse {
            id: format!(
                "mock-{}",
                self.next_interaction_id.fetch_add(1, Ordering::Relaxed)
            ),
            status: "completed".into(),
            output_text,
            function_calls: Vec::new(),
            usage: Usage {
                input_tokens,
                output_tokens,
                total_tokens: input_tokens.saturating_add(output_tokens),
            },
        })
    }

    async fn classify_audio(&self, _path: &Path) -> Result<AudioClassification, AiError> {
        Ok(AudioClassification {
            primary_class: AudioKind::Other,
            confidence: 0.5,
            contains: AudioContains::default(),
            description_ja: "Mock classification".into(),
            warnings: vec!["Generated by MockAiProvider.".into()],
        })
    }

    async fn embed_audio(&self, path: &Path) -> Result<AudioEmbedding, AiError> {
        Ok(self.embedding(path.to_string_lossy().as_bytes(), 0, 0))
    }

    async fn embed_text(&self, text: &str) -> Result<AudioEmbedding, AiError> {
        Ok(self.embedding(text.as_bytes(), 0, 0))
    }

    async fn assign_ucs_tags(
        &self,
        _path: &Path,
        candidates: &[UcsEntry],
    ) -> Result<UcsAnalysis, AiError> {
        let candidate = candidates.first().ok_or_else(|| {
            AiError::SchemaValidation("mock UCS candidates cannot be empty".into())
        })?;
        Ok(UcsAnalysis {
            candidates: vec![UcsCandidate {
                category_id: candidate.category_id.clone(),
                subcategory_id: candidate.subcategory_id.clone(),
                confidence: 0.5,
                descriptors: vec!["mock".into()],
            }],
            warnings: vec!["Generated by MockAiProvider.".into()],
        })
    }

    async fn transcribe_voice(&self, _path: &Path) -> Result<VoiceTranscript, AiError> {
        Ok(VoiceTranscript {
            language: "und".into(),
            full_text: "Mock transcript".into(),
            segments: Vec::new(),
        })
    }

    async fn transcribe_lyrics(&self, path: &Path) -> Result<VoiceTranscript, AiError> {
        self.transcribe_voice(path).await
    }
}

#[cfg(all(test, feature = "gemini"))]
mod tests {
    use super::*;

    #[tokio::test]
    async fn mock_provider_is_deterministic_and_streams_via_the_default_contract() {
        let provider = MockAiProvider::with_dimensions(4).unwrap();
        let first = provider.embed_text("impact").await.unwrap();
        let second = provider.embed_text("impact").await.unwrap();
        assert_eq!(first, second);
        assert!((first.values.iter().map(|value| value * value).sum::<f32>() - 1.0).abs() < 1e-5);

        let request = InteractionRequest {
            input: InteractionInput::Text("hello".into()),
            previous_interaction_id: None,
            system_instruction: None,
            tools: Vec::new(),
            store: false,
            max_output_tokens: Some(32),
        };
        let deltas = std::sync::Mutex::new(Vec::new());
        let response = provider
            .interact_stream(request, &|delta| deltas.lock().unwrap().push(delta))
            .await
            .unwrap();
        assert_eq!(deltas.into_inner().unwrap(), vec![response.output_text]);
    }
}
